INSERT INTO CATALOGO (DESCRIPCION_CATALOGO) VALUES ('Escuelas');
INSERT INTO CATALOGO (DESCRIPCION_CATALOGO) VALUES ('Materias');
-- Escuelas
INSERT INTO DETALLE_CATALOGO (ID_CATALOGO, COD_DETALLE_CATALOGO, DESC_DET_CATALOGO) VALUES (1, '1', 'Ciencias');
INSERT INTO DETALLE_CATALOGO (ID_CATALOGO, COD_DETALLE_CATALOGO, DESC_DET_CATALOGO) VALUES (1, '2', 'Civil');

--TABLA ESCUELAS
INSERT INTO ESCUELA VALUES(1,'CIENCIAS');
INSERT INTO ESCUELA VALUES(2,'CIVIL');
INSERT INTO ESCUELA VALUES(3,'COMPUTACION GRAFICA');

--TABLA MATERIAS
INSERT INTO MATERIA VALUES(1, 1, 'ANALISIS I');
INSERT INTO MATERIA VALUES(2, 1, 'ANALISIS II');
INSERT INTO MATERIA VALUES(3, 1, 'ANALISIS III');
INSERT INTO MATERIA VALUES(4, 1, 'FISICA I');
INSERT INTO MATERIA VALUES(5, 1, 'FISICA II');
INSERT INTO MATERIA VALUES(6, 2, 'PUENTES I');
INSERT INTO MATERIA VALUES(7, 2, 'FISICA');
INSERT INTO MATERIA VALUES(8, 3, 'DIBUJO');
INSERT INTO MATERIA VALUES(9, 3, 'DIBUJO ESPACIAL');