
INSERT INTO CATALOGO (DESCRIPCION_CATALOGO) VALUES ('Roles');

--Roles
INSERT INTO DETALLE_CATALOGO (ID_CATALOGO, COD_DETALLE_CATALOGO, DESC_DET_CATALOGO) VALUES (1, '1', 'Administrador');
INSERT INTO DETALLE_CATALOGO (ID_CATALOGO, COD_DETALLE_CATALOGO, DESC_DET_CATALOGO) VALUES (1, '2', 'Docente');
INSERT INTO DETALLE_CATALOGO (ID_CATALOGO, COD_DETALLE_CATALOGO, DESC_DET_CATALOGO) VALUES (1, '3', 'Inspector');


--TABLA ESCUELAS
INSERT INTO ESCUELA VALUES(1,'CIENCIAS');
INSERT INTO ESCUELA VALUES(2,'CIVIL');
INSERT INTO ESCUELA VALUES(3,'COMPUTACION GRAFICA');

--TABLA MATERIAS
INSERT INTO MATERIA VALUES(1, 1, 'ANALISIS I');
INSERT INTO MATERIA VALUES(2, 1, 'ANALISIS II');
INSERT INTO MATERIA VALUES(3, 1, 'ANALISIS III');
INSERT INTO MATERIA VALUES(4, 1, 'FISICA I');
INSERT INTO MATERIA VALUES(5, 1, 'FISICA II');
INSERT INTO MATERIA VALUES(6, 2, 'PUENTES I');
INSERT INTO MATERIA VALUES(7, 2, 'FISICA');
INSERT INTO MATERIA VALUES(8, 3, 'DIBUJO');
INSERT INTO MATERIA VALUES(9, 3, 'DIBUJO ESPACIAL');

--TABLA USUARIO
INSERT INTO USUARIO VALUES (1, 'admin', 'PAUL JIMENEZ','admin', '1719186262', 'A', 'A');

-- TABLA DE ROL
INSERT INTO ROL VALUES (1, 1, 'DOCENTE', 'DOCENTE', 'A');

--TABLA MENU
INSERT INTO MENU VALUES (1, NULL, 'Docente', NULL,'A');
INSERT INTO MENU VALUES (2, NULL, 'Syllabus', NULL,'A');
INSERT INTO MENU VALUES (3, NULL, 'Administracion', NULL,'A');

INSERT INTO MENU VALUES (6, 1, 'Ingresar Docente', '/pages/docente.jsf','A');
INSERT INTO MENU VALUES (7, 1, 'Ingresar Hoja de Vida', '/pages/hojaVida.jsf','A');
INSERT INTO MENU VALUES (8, 1, 'Ingresar Experiencia', '/pages/experiencia.jsf','A');
INSERT INTO MENU VALUES (9, 2, 'Ingresar Syllabus', '/pages/syllabus.jsf','A');
INSERT INTO MENU VALUES (10, 2, 'Verificar cumplimiento syllabus', '/pages/cumplimientoSyllabus.jsf','A');
INSERT INTO MENU VALUES (11, 3, 'Ingresar Usuarios', '/pages/usuarios.jsf','A');

INSERT INTO ROL_MENU VALUES (1,1,1);
INSERT INTO ROL_MENU VALUES (2,2,1);
INSERT INTO ROL_MENU VALUES (3,3,1);
INSERT INTO ROL_MENU VALUES (4,6,1);
INSERT INTO ROL_MENU VALUES (5,7,1);
INSERT INTO ROL_MENU VALUES (6,8,1);
INSERT INTO ROL_MENU VALUES (7,9,1);
INSERT INTO ROL_MENU VALUES (8,10,1);
INSERT INTO ROL_MENU VALUES (9,11,1);
